### ISSUE TITLE
android.permission.READ_PHONE_STATE

### ISSUE THREAD

**Issue by UjjwaRaijada** [paytm/paytm-allinonesdk-flutter#12]
on submitting the app on the play store, it is giving below error:

**Your APK or Android App Bundle is using permissions that require a privacy policy: (android.permission.READ_PHONE_STATE)**

the error is coming becuase of paytm_allinonesdk: ^1.0.3
on removing paytm_allinonesdk: ^1.0.3, play store is not showing any error

**Comment by UjjwaRaijada** [comment]
I have tried adding permission in AndroidManifest.xml file but it is still showing the error.

<uses-permission android:name="android.permission.READ_PHONE_STATE" />

**Comment by soumyavats** [comment]
You will have to add that privacy policy in Google Play Console

You can find this in Developer Policy Center on website play google com

Please try with this and let us know

**Comment by UjjwaRaijada** [comment]
> add that privacy policy in Google Play Console

it worked like a charm. Thanks
