### ISSUE TITLE
After payment success, page is not navigate back to app. its just showing json response.

### ISSUE THREAD

**Issue by prabha024** [paytm/paytm-allinonesdk-flutter#2]

**Comment by Neeraj0859** [comment]
have you find any solution for this?

**Comment by Neeraj0859** [comment]
@prabha024 You have to pass redirect URL in your request to navigate back to the app

**Comment by prabha024** [comment]
We need to use paytm call back URL for redirect back to app.

**Comment by UjjwaRaijada** [comment]
can anyone share the redirect url?
