### ISSUE TITLE
502 bad gateway error in webview flutter after transaction

### ISSUE THREAD

**Issue by premkumar5012002** [paytm/paytm-allinonesdk-flutter#21]
if paytm app is not installed. the paytm opens in webview. after the transaction and money is debit from account. allinonesdk webview shows 502 bad gateway problem in flutter.
![Screenshot_1635435686](https://user-images.githubusercontent.com/60777829/139289886-89003e12-bec1-4cc6-952e-d20285aff740.png)

**Comment by soumyavats** [comment]
Can you please drop a mail at integration.dev@paytm with all the details. We will be needing more info for looking into this
