### ISSUE TITLE
after starting Paytm transaction and making successful payment it is not returning to the function from where that transaction started to continue further in some cases and in some it is working as expected 

### ISSUE THREAD

**Issue by Mritunjay289** [paytm/paytm-allinonesdk-flutter#32]
getting this logs 
Error while parsing the Merchant Response
W/System.err(32147): org.json.JSONException: End of input at character 0 of 
W/System.err(32147): 	at org.json.JSONTokener.syntaxError(JSONTokener.java:460)
W/System.err(32147): 	at org.json.JSONTokener.nextValue(JSONTokener.java:101)
W/System.err(32147): 	at org.json.JSONObject.<init>(JSONObject.java:164)
W/System.err(32147): 	at org.json.JSONObject.<init>(JSONObject.java:181)
W/System.err(32147): 	at com.paytm.pgsdk.PaytmWebView.parseResponse(PaytmWebView.java:188)
W/System.err(32147): 	at com.paytm.pgsdk.PaytmWebView.access$300(PaytmWebView.java:64)
W/System.err(32147): 	at com.paytm.pgsdk.PaytmWebView$PaytmJavaScriptInterface.processResponse(PaytmWebView.java:507)
W/System.err(32147): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(32147): 	at android.os.MessageQueue.next(MessageQueue.java:336)
W/System.err(32147): 	at android.os.Looper.loop(Looper.java:197)
W/System.err(32147): 	at android.os.HandlerThread.run(HandlerThread.java:67)

D/PaytmFlutter(32147): callback is already provided

**Comment by roli18pixles** [comment]
i am  not getting  any response from All in one sdk   after payment. as well.
<img width="1036" alt="Screenshot 2024-07-05 at 4 11 04 PM" src="https://github.com/paytm/paytm-allinonesdk-flutter/assets/155063915/4e60bdab-8e40-4e31-8fdd-e05591e09ce4">
