### ISSUE TITLE
Paytm only works in debug mode.In Release mode it is not working

### ISSUE THREAD

**Issue by JenishEmpiric** [paytm/paytm-allinonesdk-flutter#8]
I have implemented paytm sdk 
but it only works if apk is in debug 
in release it is not working

**Comment by soumyavats** [comment]
In case of app crash in release mode add the below proguard rules to your project

keep class com.paytm.pgsdk.** { *; }
keep class easypay.** { *; }
keep class android.support.v7.widget.** { *; }
dontwarn android.support.v7.widget.**
white_check_mark eyes raised_hands

**Comment by JenishEmpiric** [comment]
It is Solved Now.
Thanks
